CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --master_port 12340 --nproc_per_node=8 finetune_pp_peft_trainer.py \
    --model_path /nvme2/RedPajama-INCITE-Base-3B-v1/ \
    --Train_dataset_path /nvme2/xidong_data/chessgpt_redpajama_train_no18_v2\
    --bf16 True \
    --output_dir /nvme2/xidong_data/redpajama_3b_training_result_no18_v2/ \
    --num_train_epochs 1 \
    --per_device_train_batch_size 3 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 10000 \
    --learning_rate 8e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'GPTNeoXLayer' \
    #--save_total_limit 1 \